name: Pull Tests

# Trigger the workflow on every pull request
on:
  workflow_dispatch:  # Allow manual triggering of the workflow
  pull_request:
    branches:
      - main  # Run tests on pull requests to main
  push:
    branches:
      - main  # Run security scan only on merges to main

permissions:
  security-events: write # Required for uploading SARIF files to GitHub Code Scanning
  packages: write  # Required for pushing Docker images to GitHub Container Registry


jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests with coverage report
      run: |
        pytest -n auto --cov=note_api --cov-report=xml  

    - name: Upload coverage file to codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        verbose: true

  snyk-analysis:
    # if: github.ref == 'refs/heads/main' -> if main wasn't specified above
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Specify Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'
    - name: Snyk analysis
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --sarif-file-output=snyk.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif

  build-and-push-container:
    runs-on: ubuntu-latest
    # needs: test  # Ensure this runs after the test job is completed
    # needs: snyk-analysis  # Ensure this runs after the Snyk analysis is completed
    # if: github.ref == 'refs/heads/main' -> if main wasn't specified above
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: set lowercase envs
      run: |
        echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        echo "REPO_NAME=${GITHUB_REPOSITORY##*/,,}" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest