name: Run Test Cases via Pytest
run-name: ${{ github.actor }} is testing out GitHub Actions
# Controls when the action will run
on:
  pull_request:
    types: [opened, synchronize, reopened]
# Jobs that will run in the workflow
jobs:
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.12"]
    steps:
      - run: echo "Running Test"
      - name: Check outcode
        uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }} 
      - name: Install requiremnts 
        run: |  
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - name: Test with pytest and coverage on branch ${{ github.ref }}
        run: |
          pytest tests
      - run: echo "Test with states -> ${{ job.status }}."